# Build settings
gems:
  - jemoji
  - jekyll-sitemap
  - kramdown
plugins:
  - jekyll-paginate
#   - jekyll-gzip

include:
  - _headers
  
exclude:
  - config.ru
  - Gemfile
  - Gemfile.lock
  - vendor
  - Procfile
  - Rakefile
  - README.md
  - s3_website.yml

markdown: kramdown

# Site settings
title: "Dom Barnes"
description: > # this means to ignore newlines until "email:"
   Hi I'm @domster. I write about technology mostly.
email: dom@dombarnes.com
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/ipad_coffee.jpg"

name: 'Dom Barnes'
author: 'Dom Barnes'
author_image: "/assets/images/author.jpg"

paginate:	8
# paginate_path: /page:num
permalink: /:title/
timezone:    Europe/London

# baseurl: ""
url: https://dombarnes.com # the base hostname & protocol for your site
#used to display twitter cards
twitter_handle: '@domster'

#fill in disqus shortname to use disqus
disqus: dombarnes

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/domster
    desc: Follow me on twitter
    share_url: https://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/dombarnes
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
