source 'https://rubygems.org'
ruby '2.7.0'

gem 'jekyll', '~> 4.0.0'
gem 'bourbon'
gem 'jemoji'
gem 'puma'
gem 'rack-jekyll'
gem 'rack-cache'
gem 'rake'
gem 'kramdown'
gem 'jekyll-sitemap'
gem 'jekyll-paginate'
