source 'https://rubygems.org'
 ruby '2.3.0'

gem 'jekyll', '~> 3.1.0'
gem 'bourbon'
gem 'jemoji'
gem 'puma'
gem 'rack-jekyll'
gem 'rack-cache'
gem 'rake'
gem 'kramdown'
gem 'jekyll-sitemap'
gem 'jekyll-paginate'
